version: "3"
services:
    test_db:
        image: mysql
        container_name: test_db
        tty: true
        ports:
            - "3309:3306"
        volumes:
            - ./test_db:/var/lib/mysql
        environment:
            TZ: Europe/Kiev
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: test_db
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        networks:
            - test
networks:
    test:
